name: Build Icarus Verilog docker image and upload to DockerHub

on:
  push:
    tags:
      - '*'  
      
env:
  DOCKER_USER: ${{ secrets.DOCKER_HUB_ID }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}
  DOCKER_IMAGE_NAME: 'adithya.yuri/icarus_verilog:${GITHUB_REF#refs/*/}'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repo
      uses: actions/checkout@v3
    
    - name: Build the image
      run: |
        docker build -t ${{ env.DOCKER_IMAGE_NAME }} --build-arg BUILD_DATE=$(date +'%Y-%m-%dT%H:%M:%S') .
        
    - name: Docker Login
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD

    - name: Docker push
      run: |
        docker push ${{ env.DOCKER_IMAGE_NAME }}
