name: Build Icarus Verilog docker image and upload to DockerHub

on:
  push:
    tags:
      - '*'  
      
env:
  DOCKER_USER: ${{ secrets.DOCKER_HUB_ID }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}
  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repo
      uses: actions/checkout@v3
    
    - name: Build the image
      env:
        DOCKER_IMAGE_NAME: 'adithya.yuri/icarus_verilog:${GITHUB_REF#refs/*/}'
      run: echo ${{ env.DOCKER_IMAGE_NAME }}
